name: Bug report
description: If you've confirmed something is broken, create a bug report.
title: "[Bug report] <description>"
labels: [needs triage]
body:
- type: checkboxes
  id: prereqs
  attributes:
    label: Is there an existing issue for this?
    description: Please check whether an issue already exists for the bug you encountered.
    options:
      - label: I have searched the existing issues
        required: true
- type: checkboxes
  id: update-title
  attributes:
    label: Update the issue title
    description: Replace `<description> with a description of the bug`
    options:
      - label: I have updated the title
        required: true
- type: textarea
  attributes:
    label: Links
    description: |
      Any links of references that will give us more context about the issue you are encountering
  validations:
    required: false
- type: textarea
  attributes:
    label: Details
    description: |
      Write up your bug.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
